// Copyright (c) Craig Williams, MathWiz86

using System;
using System.Collections.Generic;

/// <summary>
/// The list of <see cref="PlayerStat"/>s to display. Edit <see cref="CalculatorDisplayedStats._playerStats"/> to
/// add or remove more stats to be displayed.
/// </summary>
public sealed partial class CalculatorDisplayedStats
{
    /// <summary>
    /// Iterates through all <see cref="_playerStats"/>.
    /// </summary>
    /// <param name="inAction">The <see cref="Action{T1, T2}"/> called for each stat. Passes the index and the stat.</param>
    public void IterateDisplayedStats(Action<int, PlayerStat> inAction)
    {
        if (_playerStats == null || inAction == null)
            return;

        for (int i = 0; i < _playerStats.Count; ++i)
        {
            inAction.Invoke(i, _playerStats[i]);
        }
    }

    /// <summary>
    /// Iterates through all <see cref="_playerStats"/> that can be displayed on the given page.
    /// </summary>
    /// <param name="pageIndex">The page index, starting at 0.</param>
    /// <param name="statsPerPage">The number of stats to count off for this page.</param>
    /// <param name="inAction">The <see cref="Action{T1, T2}"/> called for each stat. Passes the index and the stat.</param>
    public void IterateDisplayedStats(int pageIndex, int statsPerPage, Action<int, PlayerStat> inAction)
    {
        if (_playerStats == null || inAction == null || pageIndex < 0)
            return;

        int startIndex = pageIndex * statsPerPage;
        int lastIndex = Math.Min(_playerStats.Count, startIndex + statsPerPage);
        for (int i = startIndex; i < lastIndex; ++i)
        {
            inAction.Invoke(i, _playerStats[i]);
        }
    }

    /// <summary>
    /// Gets the number of <see cref="_playerStats"/>.
    /// </summary>
    /// <returns>Returns the <see cref="_playerStats"/> count.</returns>
    public int GetStatCount()
    {
        return _playerStats?.Count ?? 0;
    }
}

// Separated to keep these long lists towards the bottom of the file.
public sealed partial class CalculatorDisplayedStats
{
    // The below are common filters used in the default stat list.
    private static readonly PlayerStatCommonFilter FilterBattleSpirit = new PlayerStatCommonFilter(BattleType.Spirit);
    private static readonly PlayerStatCommonFilter FilterBattleFighter = new PlayerStatCommonFilter(BattleType.Fighter);
    private static readonly PlayerStatCommonFilter FilterBattleBoss = new PlayerStatCommonFilter(BattleType.Boss);

    private static readonly PlayerStatCommonFilter FilterAffinityNeutral = new PlayerStatCommonFilter(null, SpiritAffinity.Neutral);
    private static readonly PlayerStatCommonFilter FilterAffinityAttack = new PlayerStatCommonFilter(null, SpiritAffinity.Attack);
    private static readonly PlayerStatCommonFilter FilterAffinityShield = new PlayerStatCommonFilter(null, SpiritAffinity.Shield);
    private static readonly PlayerStatCommonFilter FilterAffinityGrab = new PlayerStatCommonFilter(null, SpiritAffinity.Grab);

    private static readonly PlayerStatCommonFilter FilterSpiritPrimary = new PlayerStatCommonFilter(BattleType.Spirit, null, SpiritType.Primary);
    private static readonly PlayerStatCommonFilter FilterSpiritSupport = new PlayerStatCommonFilter(BattleType.Spirit, null, SpiritType.Support);
    private static readonly PlayerStatCommonFilter FilterSpiritMaster = new PlayerStatCommonFilter(BattleType.Spirit, null, SpiritType.Master);

    private static readonly PlayerStatCommonFilter FilterSpiritNeutral = new PlayerStatCommonFilter(BattleType.Spirit, SpiritAffinity.Neutral);
    private static readonly PlayerStatCommonFilter FilterSpiritAttack = new PlayerStatCommonFilter(BattleType.Spirit, SpiritAffinity.Attack);
    private static readonly PlayerStatCommonFilter FilterSpiritShield = new PlayerStatCommonFilter(BattleType.Spirit, SpiritAffinity.Shield);
    private static readonly PlayerStatCommonFilter FilterSpiritGrab = new PlayerStatCommonFilter(BattleType.Spirit, SpiritAffinity.Grab);

    private static readonly PlayerStatCommonFilter FilterPrimaryNeutral = new PlayerStatCommonFilter(BattleType.Spirit, SpiritAffinity.Neutral, SpiritType.Primary);
    private static readonly PlayerStatCommonFilter FilterPrimaryAttack = new PlayerStatCommonFilter(BattleType.Spirit, SpiritAffinity.Attack, SpiritType.Primary);
    private static readonly PlayerStatCommonFilter FilterPrimaryShield = new PlayerStatCommonFilter(BattleType.Spirit, SpiritAffinity.Shield, SpiritType.Primary);
    private static readonly PlayerStatCommonFilter FilterPrimaryGrab = new PlayerStatCommonFilter(BattleType.Spirit, SpiritAffinity.Grab, SpiritType.Primary);

    private static readonly PlayerStatCommonFilter FilterSupportNeutral = new PlayerStatCommonFilter(BattleType.Spirit, SpiritAffinity.Neutral, SpiritType.Support);
    private static readonly PlayerStatCommonFilter FilterSupportAttack = new PlayerStatCommonFilter(BattleType.Spirit, SpiritAffinity.Attack, SpiritType.Support);
    private static readonly PlayerStatCommonFilter FilterSupportShield = new PlayerStatCommonFilter(BattleType.Spirit, SpiritAffinity.Shield, SpiritType.Support);
    private static readonly PlayerStatCommonFilter FilterSupportGrab = new PlayerStatCommonFilter(BattleType.Spirit, SpiritAffinity.Grab, SpiritType.Support);

    private static readonly PlayerStatCommonFilter FilterFighterNeutral = new PlayerStatCommonFilter(BattleType.Fighter, SpiritAffinity.Neutral);
    private static readonly PlayerStatCommonFilter FilterFighterAttack = new PlayerStatCommonFilter(BattleType.Fighter, SpiritAffinity.Attack);
    private static readonly PlayerStatCommonFilter FilterFighterShield = new PlayerStatCommonFilter(BattleType.Fighter, SpiritAffinity.Shield);
    private static readonly PlayerStatCommonFilter FilterFighterGrab = new PlayerStatCommonFilter(BattleType.Fighter, SpiritAffinity.Grab);

    private static readonly PlayerStatCommonalityFilter<string> FilterCommonalitySpirit = new PlayerStatCommonalityFilter<string>(null, BattleType.Spirit);
    private static readonly PlayerStatCommonalityFilter<string> FilterCommonalityValidAbility = new PlayerStatCommonalityFilter<string>(new List<string> { "None", "Enhanced" }, BattleType.Spirit);

    /// <summary>Edit this list to add new stats to display in the <see cref="MenuPlayerStats"/>.</summary>
    private readonly List<PlayerStat> _playerStats = new List<PlayerStat>
                                                     {
                                                         new PlayerStatBattlesTotal(null),
                                                         new PlayerStatBattlesTotal(FilterBattleSpirit),
                                                         new PlayerStatBattlesTotal(FilterBattleFighter),
                                                         new PlayerStatBattlesTotal(FilterBattleBoss),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattlesUnique(null),
                                                         new PlayerStatBattlesUnique(FilterBattleSpirit),
                                                         new PlayerStatBattlesUnique(FilterBattleFighter),
                                                         new PlayerStatBattlesUnique(FilterBattleBoss),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattleWins(false, null),
                                                         new PlayerStatBattleWins(false, FilterBattleSpirit),
                                                         new PlayerStatBattleWins(false, FilterBattleFighter),
                                                         new PlayerStatBattleWins(false, FilterBattleBoss),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattleWins(true, null),
                                                         new PlayerStatBattleWins(true, FilterBattleSpirit),
                                                         new PlayerStatBattleWins(true, FilterBattleFighter),
                                                         new PlayerStatBattleWins(true, FilterBattleBoss),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattleWinsSolo(false, null),
                                                         new PlayerStatBattleWinsSolo(false, FilterBattleSpirit),
                                                         new PlayerStatBattleWinsSolo(false, FilterBattleFighter),
                                                         new PlayerStatBattleWinsSolo(false, FilterBattleBoss),
                                                         new PlayerStatBattleWinsSolo(true, null),
                                                         new PlayerStatBattleWinsSolo(true, FilterBattleSpirit),
                                                         new PlayerStatBattleWinsSolo(true, FilterBattleFighter),
                                                         new PlayerStatBattleWinsSolo(true, FilterBattleBoss),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattleLosses(null),
                                                         new PlayerStatBattleLosses(FilterBattleSpirit),
                                                         new PlayerStatBattleLosses(FilterBattleFighter),
                                                         new PlayerStatBattleLosses(FilterBattleBoss),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattleLossesUnique(null),
                                                         new PlayerStatBattleLossesUnique(FilterBattleSpirit),
                                                         new PlayerStatBattleLossesUnique(FilterBattleFighter),
                                                         new PlayerStatBattleLossesUnique(FilterBattleBoss),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatSaviorWins(1, false, null),
                                                         new PlayerStatSaviorWins(1, false, FilterBattleSpirit),
                                                         new PlayerStatSaviorWins(1, false, FilterBattleFighter),
                                                         new PlayerStatSaviorWins(1, false, FilterBattleBoss),
                                                         new PlayerStatSaviorWins(1, true, null),
                                                         new PlayerStatSaviorWins(1, true, FilterBattleSpirit),
                                                         new PlayerStatSaviorWins(1, true, FilterBattleFighter),
                                                         new PlayerStatSaviorWins(1, true, FilterBattleBoss),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatCommonalitySeries(true, 1, 1, FilterCommonalitySpirit),
                                                         new PlayerStatCommonalitySeries(true, 1, 2, FilterCommonalitySpirit),
                                                         new PlayerStatCommonalitySeries(true, 1, 3, FilterCommonalitySpirit),
                                                         new PlayerStatCommonalitySeries(false, 1, 1, FilterCommonalitySpirit),
                                                         new PlayerStatCommonalitySeries(false, 1, 2, FilterCommonalitySpirit),
                                                         new PlayerStatCommonalitySeries(false, 1, 3, FilterCommonalitySpirit),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatCommonalityAbility(true, 1, 1, FilterCommonalityValidAbility),
                                                         new PlayerStatCommonalityAbility(true, 1, 2, FilterCommonalityValidAbility),
                                                         new PlayerStatCommonalityAbility(true, 1, 3, FilterCommonalityValidAbility),
                                                         new PlayerStatCommonalityAbility(false, 3, 1, FilterCommonalitySpirit),
                                                         new PlayerStatCommonalityAbility(false, 3, 2, FilterCommonalitySpirit),
                                                         new PlayerStatCommonalityAbility(false, 3, 3, FilterCommonalitySpirit),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatToughBattle(StatType.Single, 1, null),
                                                         new PlayerStatToughBattle(StatType.Single, 2, null),
                                                         new PlayerStatToughBattle(StatType.Single, 3, null),
                                                         new PlayerStatToughBattle(StatType.Single, 4, null),
                                                         new PlayerStatToughBattle(StatType.Single, 5, null),
                                                         new PlayerStatToughBattle(StatType.Single, 6, null),
                                                         new PlayerStatToughBattle(StatType.Single, 7, null),
                                                         new PlayerStatToughBattle(StatType.Single, 8, null),
                                                         new PlayerStatToughBattle(StatType.Single, 9, null),
                                                         new PlayerStatToughBattle(StatType.Single, 10, null),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatToughBattle(StatType.Comparison, 1, null),
                                                         new PlayerStatToughBattle(StatType.Comparison, 2, null),
                                                         new PlayerStatToughBattle(StatType.Comparison, 3, null),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatSpiritPower(false, null),
                                                         new PlayerStatSpiritPower(false, FilterBattleSpirit),
                                                         new PlayerStatSpiritPower(false, FilterBattleFighter),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatSpiritPower(true, null),
                                                         new PlayerStatSpiritPower(true, FilterBattleSpirit),
                                                         new PlayerStatSpiritPower(true, FilterBattleFighter),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatSpiritClass(false, null),
                                                         new PlayerStatSpiritClass(false, FilterAffinityNeutral),
                                                         new PlayerStatSpiritClass(false, FilterAffinityAttack),
                                                         new PlayerStatSpiritClass(false, FilterAffinityShield),
                                                         new PlayerStatSpiritClass(false, FilterAffinityGrab),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatSpiritClass(true, null),
                                                         new PlayerStatSpiritClass(true, FilterAffinityNeutral),
                                                         new PlayerStatSpiritClass(true, FilterAffinityAttack),
                                                         new PlayerStatSpiritClass(true, FilterAffinityShield),
                                                         new PlayerStatSpiritClass(true, FilterAffinityGrab),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatDivider("Verbose Stats"),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattlesTotal(FilterSpiritPrimary),
                                                         new PlayerStatBattlesTotal(FilterSpiritSupport),
                                                         new PlayerStatBattlesTotal(FilterSpiritMaster),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattlesTotal(FilterAffinityNeutral),
                                                         new PlayerStatBattlesTotal(FilterSpiritNeutral),
                                                         new PlayerStatBattlesTotal(FilterPrimaryNeutral),
                                                         new PlayerStatBattlesTotal(FilterSupportNeutral),
                                                         new PlayerStatBattlesTotal(FilterFighterNeutral),
                                                         new PlayerStatBattlesTotal(FilterAffinityAttack),
                                                         new PlayerStatBattlesTotal(FilterSpiritAttack),
                                                         new PlayerStatBattlesTotal(FilterPrimaryAttack),
                                                         new PlayerStatBattlesTotal(FilterSupportAttack),
                                                         new PlayerStatBattlesTotal(FilterFighterAttack),
                                                         new PlayerStatBattlesTotal(FilterAffinityShield),
                                                         new PlayerStatBattlesTotal(FilterSpiritShield),
                                                         new PlayerStatBattlesTotal(FilterPrimaryShield),
                                                         new PlayerStatBattlesTotal(FilterSupportShield),
                                                         new PlayerStatBattlesTotal(FilterFighterShield),
                                                         new PlayerStatBattlesTotal(FilterAffinityGrab),
                                                         new PlayerStatBattlesTotal(FilterSpiritGrab),
                                                         new PlayerStatBattlesTotal(FilterPrimaryGrab),
                                                         new PlayerStatBattlesTotal(FilterSupportGrab),
                                                         new PlayerStatBattlesTotal(FilterFighterGrab),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattlesUnique(FilterSpiritPrimary),
                                                         new PlayerStatBattlesUnique(FilterSpiritSupport),
                                                         new PlayerStatBattlesUnique(FilterSpiritMaster),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattlesUnique(FilterAffinityNeutral),
                                                         new PlayerStatBattlesUnique(FilterSpiritNeutral),
                                                         new PlayerStatBattlesUnique(FilterPrimaryNeutral),
                                                         new PlayerStatBattlesUnique(FilterSupportNeutral),
                                                         new PlayerStatBattlesUnique(FilterFighterNeutral),
                                                         new PlayerStatBattlesUnique(FilterAffinityAttack),
                                                         new PlayerStatBattlesUnique(FilterSpiritAttack),
                                                         new PlayerStatBattlesUnique(FilterPrimaryAttack),
                                                         new PlayerStatBattlesUnique(FilterSupportAttack),
                                                         new PlayerStatBattlesUnique(FilterFighterAttack),
                                                         new PlayerStatBattlesUnique(FilterAffinityShield),
                                                         new PlayerStatBattlesUnique(FilterSpiritShield),
                                                         new PlayerStatBattlesUnique(FilterPrimaryShield),
                                                         new PlayerStatBattlesUnique(FilterSupportShield),
                                                         new PlayerStatBattlesUnique(FilterFighterShield),
                                                         new PlayerStatBattlesUnique(FilterAffinityGrab),
                                                         new PlayerStatBattlesUnique(FilterSpiritGrab),
                                                         new PlayerStatBattlesUnique(FilterPrimaryGrab),
                                                         new PlayerStatBattlesUnique(FilterSupportGrab),
                                                         new PlayerStatBattlesUnique(FilterFighterGrab),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattleWins(false, FilterSpiritPrimary),
                                                         new PlayerStatBattleWins(false, FilterSpiritSupport),
                                                         new PlayerStatBattleWins(false, FilterSpiritMaster),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattleWins(false, FilterAffinityNeutral),
                                                         new PlayerStatBattleWins(false, FilterSpiritNeutral),
                                                         new PlayerStatBattleWins(false, FilterPrimaryNeutral),
                                                         new PlayerStatBattleWins(false, FilterSupportNeutral),
                                                         new PlayerStatBattleWins(false, FilterFighterNeutral),
                                                         new PlayerStatBattleWins(false, FilterAffinityAttack),
                                                         new PlayerStatBattleWins(false, FilterSpiritAttack),
                                                         new PlayerStatBattleWins(false, FilterPrimaryAttack),
                                                         new PlayerStatBattleWins(false, FilterSupportAttack),
                                                         new PlayerStatBattleWins(false, FilterFighterAttack),
                                                         new PlayerStatBattleWins(false, FilterAffinityShield),
                                                         new PlayerStatBattleWins(false, FilterSpiritShield),
                                                         new PlayerStatBattleWins(false, FilterPrimaryShield),
                                                         new PlayerStatBattleWins(false, FilterSupportShield),
                                                         new PlayerStatBattleWins(false, FilterFighterShield),
                                                         new PlayerStatBattleWins(false, FilterAffinityGrab),
                                                         new PlayerStatBattleWins(false, FilterSpiritGrab),
                                                         new PlayerStatBattleWins(false, FilterPrimaryGrab),
                                                         new PlayerStatBattleWins(false, FilterSupportGrab),
                                                         new PlayerStatBattleWins(false, FilterFighterGrab),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattleWins(true, FilterSpiritPrimary),
                                                         new PlayerStatBattleWins(true, FilterSpiritSupport),
                                                         new PlayerStatBattleWins(true, FilterSpiritMaster),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattleWins(true, FilterAffinityNeutral),
                                                         new PlayerStatBattleWins(true, FilterSpiritNeutral),
                                                         new PlayerStatBattleWins(true, FilterPrimaryNeutral),
                                                         new PlayerStatBattleWins(true, FilterSupportNeutral),
                                                         new PlayerStatBattleWins(true, FilterFighterNeutral),
                                                         new PlayerStatBattleWins(true, FilterAffinityAttack),
                                                         new PlayerStatBattleWins(true, FilterSpiritAttack),
                                                         new PlayerStatBattleWins(true, FilterPrimaryAttack),
                                                         new PlayerStatBattleWins(true, FilterSupportAttack),
                                                         new PlayerStatBattleWins(true, FilterFighterAttack),
                                                         new PlayerStatBattleWins(true, FilterAffinityShield),
                                                         new PlayerStatBattleWins(true, FilterSpiritShield),
                                                         new PlayerStatBattleWins(true, FilterPrimaryShield),
                                                         new PlayerStatBattleWins(true, FilterSupportShield),
                                                         new PlayerStatBattleWins(true, FilterFighterShield),
                                                         new PlayerStatBattleWins(true, FilterAffinityGrab),
                                                         new PlayerStatBattleWins(true, FilterSpiritGrab),
                                                         new PlayerStatBattleWins(true, FilterPrimaryGrab),
                                                         new PlayerStatBattleWins(true, FilterSupportGrab),
                                                         new PlayerStatBattleWins(true, FilterFighterGrab),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattleWinsSolo(false, FilterSpiritPrimary),
                                                         new PlayerStatBattleWinsSolo(false, FilterSpiritSupport),
                                                         new PlayerStatBattleWinsSolo(false, FilterSpiritMaster),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattleWinsSolo(false, FilterAffinityNeutral),
                                                         new PlayerStatBattleWinsSolo(false, FilterSpiritNeutral),
                                                         new PlayerStatBattleWinsSolo(false, FilterPrimaryNeutral),
                                                         new PlayerStatBattleWinsSolo(false, FilterSupportNeutral),
                                                         new PlayerStatBattleWinsSolo(false, FilterFighterNeutral),
                                                         new PlayerStatBattleWinsSolo(false, FilterAffinityAttack),
                                                         new PlayerStatBattleWinsSolo(false, FilterSpiritAttack),
                                                         new PlayerStatBattleWinsSolo(false, FilterPrimaryAttack),
                                                         new PlayerStatBattleWinsSolo(false, FilterSupportAttack),
                                                         new PlayerStatBattleWinsSolo(false, FilterFighterAttack),
                                                         new PlayerStatBattleWinsSolo(false, FilterAffinityShield),
                                                         new PlayerStatBattleWinsSolo(false, FilterSpiritShield),
                                                         new PlayerStatBattleWinsSolo(false, FilterPrimaryShield),
                                                         new PlayerStatBattleWinsSolo(false, FilterSupportShield),
                                                         new PlayerStatBattleWinsSolo(false, FilterFighterShield),
                                                         new PlayerStatBattleWinsSolo(false, FilterAffinityGrab),
                                                         new PlayerStatBattleWinsSolo(false, FilterSpiritGrab),
                                                         new PlayerStatBattleWinsSolo(false, FilterPrimaryGrab),
                                                         new PlayerStatBattleWinsSolo(false, FilterSupportGrab),
                                                         new PlayerStatBattleWinsSolo(false, FilterFighterGrab),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattleWinsSolo(true, FilterSpiritPrimary),
                                                         new PlayerStatBattleWinsSolo(true, FilterSpiritSupport),
                                                         new PlayerStatBattleWinsSolo(true, FilterSpiritMaster),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattleWinsSolo(true, FilterAffinityNeutral),
                                                         new PlayerStatBattleWinsSolo(true, FilterSpiritNeutral),
                                                         new PlayerStatBattleWinsSolo(true, FilterPrimaryNeutral),
                                                         new PlayerStatBattleWinsSolo(true, FilterSupportNeutral),
                                                         new PlayerStatBattleWinsSolo(true, FilterFighterNeutral),
                                                         new PlayerStatBattleWinsSolo(true, FilterAffinityAttack),
                                                         new PlayerStatBattleWinsSolo(true, FilterSpiritAttack),
                                                         new PlayerStatBattleWinsSolo(true, FilterPrimaryAttack),
                                                         new PlayerStatBattleWinsSolo(true, FilterSupportAttack),
                                                         new PlayerStatBattleWinsSolo(true, FilterFighterAttack),
                                                         new PlayerStatBattleWinsSolo(true, FilterAffinityShield),
                                                         new PlayerStatBattleWinsSolo(true, FilterSpiritShield),
                                                         new PlayerStatBattleWinsSolo(true, FilterPrimaryShield),
                                                         new PlayerStatBattleWinsSolo(true, FilterSupportShield),
                                                         new PlayerStatBattleWinsSolo(true, FilterFighterShield),
                                                         new PlayerStatBattleWinsSolo(true, FilterAffinityGrab),
                                                         new PlayerStatBattleWinsSolo(true, FilterSpiritGrab),
                                                         new PlayerStatBattleWinsSolo(true, FilterPrimaryGrab),
                                                         new PlayerStatBattleWinsSolo(true, FilterSupportGrab),
                                                         new PlayerStatBattleWinsSolo(true, FilterFighterGrab),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattleLosses(FilterSpiritPrimary),
                                                         new PlayerStatBattleLosses(FilterSpiritSupport),
                                                         new PlayerStatBattleLosses(FilterSpiritMaster),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattleLosses(FilterAffinityNeutral),
                                                         new PlayerStatBattleLosses(FilterSpiritNeutral),
                                                         new PlayerStatBattleLosses(FilterPrimaryNeutral),
                                                         new PlayerStatBattleLosses(FilterSupportNeutral),
                                                         new PlayerStatBattleLosses(FilterFighterNeutral),
                                                         new PlayerStatBattleLosses(FilterAffinityAttack),
                                                         new PlayerStatBattleLosses(FilterSpiritAttack),
                                                         new PlayerStatBattleLosses(FilterPrimaryAttack),
                                                         new PlayerStatBattleLosses(FilterSupportAttack),
                                                         new PlayerStatBattleLosses(FilterFighterAttack),
                                                         new PlayerStatBattleLosses(FilterAffinityShield),
                                                         new PlayerStatBattleLosses(FilterSpiritShield),
                                                         new PlayerStatBattleLosses(FilterPrimaryShield),
                                                         new PlayerStatBattleLosses(FilterSupportShield),
                                                         new PlayerStatBattleLosses(FilterFighterShield),
                                                         new PlayerStatBattleLosses(FilterAffinityGrab),
                                                         new PlayerStatBattleLosses(FilterSpiritGrab),
                                                         new PlayerStatBattleLosses(FilterPrimaryGrab),
                                                         new PlayerStatBattleLosses(FilterSupportGrab),
                                                         new PlayerStatBattleLosses(FilterFighterGrab),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattleLossesUnique(FilterSpiritPrimary),
                                                         new PlayerStatBattleLossesUnique(FilterSpiritSupport),
                                                         new PlayerStatBattleLossesUnique(FilterSpiritMaster),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatBattleLossesUnique(FilterAffinityNeutral),
                                                         new PlayerStatBattleLossesUnique(FilterSpiritNeutral),
                                                         new PlayerStatBattleLossesUnique(FilterPrimaryNeutral),
                                                         new PlayerStatBattleLossesUnique(FilterSupportNeutral),
                                                         new PlayerStatBattleLossesUnique(FilterFighterNeutral),
                                                         new PlayerStatBattleLossesUnique(FilterAffinityAttack),
                                                         new PlayerStatBattleLossesUnique(FilterSpiritAttack),
                                                         new PlayerStatBattleLossesUnique(FilterPrimaryAttack),
                                                         new PlayerStatBattleLossesUnique(FilterSupportAttack),
                                                         new PlayerStatBattleLossesUnique(FilterFighterAttack),
                                                         new PlayerStatBattleLossesUnique(FilterAffinityShield),
                                                         new PlayerStatBattleLossesUnique(FilterSpiritShield),
                                                         new PlayerStatBattleLossesUnique(FilterPrimaryShield),
                                                         new PlayerStatBattleLossesUnique(FilterSupportShield),
                                                         new PlayerStatBattleLossesUnique(FilterFighterShield),
                                                         new PlayerStatBattleLossesUnique(FilterAffinityGrab),
                                                         new PlayerStatBattleLossesUnique(FilterSpiritGrab),
                                                         new PlayerStatBattleLossesUnique(FilterPrimaryGrab),
                                                         new PlayerStatBattleLossesUnique(FilterSupportGrab),
                                                         new PlayerStatBattleLossesUnique(FilterFighterGrab),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatSaviorWins(1, false, FilterSpiritPrimary),
                                                         new PlayerStatSaviorWins(1, false, FilterSpiritSupport),
                                                         new PlayerStatSaviorWins(1, false, FilterSpiritMaster),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatSaviorWins(1, false, FilterAffinityNeutral),
                                                         new PlayerStatSaviorWins(1, false, FilterSpiritNeutral),
                                                         new PlayerStatSaviorWins(1, false, FilterPrimaryNeutral),
                                                         new PlayerStatSaviorWins(1, false, FilterSupportNeutral),
                                                         new PlayerStatSaviorWins(1, false, FilterFighterNeutral),
                                                         new PlayerStatSaviorWins(1, false, FilterAffinityAttack),
                                                         new PlayerStatSaviorWins(1, false, FilterSpiritAttack),
                                                         new PlayerStatSaviorWins(1, false, FilterPrimaryAttack),
                                                         new PlayerStatSaviorWins(1, false, FilterSupportAttack),
                                                         new PlayerStatSaviorWins(1, false, FilterFighterAttack),
                                                         new PlayerStatSaviorWins(1, false, FilterAffinityShield),
                                                         new PlayerStatSaviorWins(1, false, FilterSpiritShield),
                                                         new PlayerStatSaviorWins(1, false, FilterPrimaryShield),
                                                         new PlayerStatSaviorWins(1, false, FilterSupportShield),
                                                         new PlayerStatSaviorWins(1, false, FilterFighterShield),
                                                         new PlayerStatSaviorWins(1, false, FilterAffinityGrab),
                                                         new PlayerStatSaviorWins(1, false, FilterSpiritGrab),
                                                         new PlayerStatSaviorWins(1, false, FilterPrimaryGrab),
                                                         new PlayerStatSaviorWins(1, false, FilterSupportGrab),
                                                         new PlayerStatSaviorWins(1, false, FilterFighterGrab),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatSaviorWins(1, true, FilterSpiritPrimary),
                                                         new PlayerStatSaviorWins(1, true, FilterSpiritSupport),
                                                         new PlayerStatSaviorWins(1, true, FilterSpiritMaster),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatSaviorWins(1, true, FilterAffinityNeutral),
                                                         new PlayerStatSaviorWins(1, true, FilterSpiritNeutral),
                                                         new PlayerStatSaviorWins(1, true, FilterPrimaryNeutral),
                                                         new PlayerStatSaviorWins(1, true, FilterSupportNeutral),
                                                         new PlayerStatSaviorWins(1, true, FilterFighterNeutral),
                                                         new PlayerStatSaviorWins(1, true, FilterAffinityAttack),
                                                         new PlayerStatSaviorWins(1, true, FilterSpiritAttack),
                                                         new PlayerStatSaviorWins(1, true, FilterPrimaryAttack),
                                                         new PlayerStatSaviorWins(1, true, FilterSupportAttack),
                                                         new PlayerStatSaviorWins(1, true, FilterFighterAttack),
                                                         new PlayerStatSaviorWins(1, true, FilterAffinityShield),
                                                         new PlayerStatSaviorWins(1, true, FilterSpiritShield),
                                                         new PlayerStatSaviorWins(1, true, FilterPrimaryShield),
                                                         new PlayerStatSaviorWins(1, true, FilterSupportShield),
                                                         new PlayerStatSaviorWins(1, true, FilterFighterShield),
                                                         new PlayerStatSaviorWins(1, true, FilterAffinityGrab),
                                                         new PlayerStatSaviorWins(1, true, FilterSpiritGrab),
                                                         new PlayerStatSaviorWins(1, true, FilterPrimaryGrab),
                                                         new PlayerStatSaviorWins(1, true, FilterSupportGrab),
                                                         new PlayerStatSaviorWins(1, true, FilterFighterGrab),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatSpiritPower(false, FilterSpiritPrimary),
                                                         new PlayerStatSpiritPower(false, FilterSpiritSupport),
                                                         new PlayerStatSpiritPower(false, FilterSpiritMaster),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatSpiritPower(false, FilterAffinityNeutral),
                                                         new PlayerStatSpiritPower(false, FilterSpiritNeutral),
                                                         new PlayerStatSpiritPower(false, FilterPrimaryNeutral),
                                                         new PlayerStatSpiritPower(false, FilterSupportNeutral),
                                                         new PlayerStatSpiritPower(false, FilterFighterNeutral),
                                                         new PlayerStatSpiritPower(false, FilterAffinityAttack),
                                                         new PlayerStatSpiritPower(false, FilterSpiritAttack),
                                                         new PlayerStatSpiritPower(false, FilterPrimaryAttack),
                                                         new PlayerStatSpiritPower(false, FilterSupportAttack),
                                                         new PlayerStatSpiritPower(false, FilterFighterAttack),
                                                         new PlayerStatSpiritPower(false, FilterAffinityShield),
                                                         new PlayerStatSpiritPower(false, FilterSpiritShield),
                                                         new PlayerStatSpiritPower(false, FilterPrimaryShield),
                                                         new PlayerStatSpiritPower(false, FilterSupportShield),
                                                         new PlayerStatSpiritPower(false, FilterFighterShield),
                                                         new PlayerStatSpiritPower(false, FilterAffinityGrab),
                                                         new PlayerStatSpiritPower(false, FilterSpiritGrab),
                                                         new PlayerStatSpiritPower(false, FilterPrimaryGrab),
                                                         new PlayerStatSpiritPower(false, FilterSupportGrab),
                                                         new PlayerStatSpiritPower(false, FilterFighterGrab),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatSpiritPower(true, FilterSpiritPrimary),
                                                         new PlayerStatSpiritPower(true, FilterSpiritSupport),
                                                         new PlayerStatSpiritPower(true, FilterSpiritMaster),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatSpiritPower(true, FilterAffinityNeutral),
                                                         new PlayerStatSpiritPower(true, FilterSpiritNeutral),
                                                         new PlayerStatSpiritPower(true, FilterPrimaryNeutral),
                                                         new PlayerStatSpiritPower(true, FilterSupportNeutral),
                                                         new PlayerStatSpiritPower(true, FilterFighterNeutral),
                                                         new PlayerStatSpiritPower(true, FilterAffinityAttack),
                                                         new PlayerStatSpiritPower(true, FilterSpiritAttack),
                                                         new PlayerStatSpiritPower(true, FilterPrimaryAttack),
                                                         new PlayerStatSpiritPower(true, FilterSupportAttack),
                                                         new PlayerStatSpiritPower(true, FilterFighterAttack),
                                                         new PlayerStatSpiritPower(true, FilterAffinityShield),
                                                         new PlayerStatSpiritPower(true, FilterSpiritShield),
                                                         new PlayerStatSpiritPower(true, FilterPrimaryShield),
                                                         new PlayerStatSpiritPower(true, FilterSupportShield),
                                                         new PlayerStatSpiritPower(true, FilterFighterShield),
                                                         new PlayerStatSpiritPower(true, FilterAffinityGrab),
                                                         new PlayerStatSpiritPower(true, FilterSpiritGrab),
                                                         new PlayerStatSpiritPower(true, FilterPrimaryGrab),
                                                         new PlayerStatSpiritPower(true, FilterSupportGrab),
                                                         new PlayerStatSpiritPower(true, FilterFighterGrab),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatSpiritClass(false, FilterSpiritPrimary),
                                                         new PlayerStatSpiritClass(false, FilterSpiritSupport),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatSpiritClass(false, FilterAffinityNeutral),
                                                         new PlayerStatSpiritClass(false, FilterSpiritNeutral),
                                                         new PlayerStatSpiritClass(false, FilterPrimaryNeutral),
                                                         new PlayerStatSpiritClass(false, FilterSupportNeutral),
                                                         new PlayerStatSpiritClass(false, FilterAffinityAttack),
                                                         new PlayerStatSpiritClass(false, FilterSpiritAttack),
                                                         new PlayerStatSpiritClass(false, FilterPrimaryAttack),
                                                         new PlayerStatSpiritClass(false, FilterSupportAttack),
                                                         new PlayerStatSpiritClass(false, FilterAffinityShield),
                                                         new PlayerStatSpiritClass(false, FilterSpiritShield),
                                                         new PlayerStatSpiritClass(false, FilterPrimaryShield),
                                                         new PlayerStatSpiritClass(false, FilterSupportShield),
                                                         new PlayerStatSpiritClass(false, FilterAffinityGrab),
                                                         new PlayerStatSpiritClass(false, FilterSpiritGrab),
                                                         new PlayerStatSpiritClass(false, FilterPrimaryGrab),
                                                         new PlayerStatSpiritClass(false, FilterSupportGrab),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatSpiritClass(true, FilterSpiritPrimary),
                                                         new PlayerStatSpiritClass(true, FilterSpiritSupport),
                                                         new PlayerStatDivider(),
                                                         new PlayerStatSpiritClass(true, FilterAffinityNeutral),
                                                         new PlayerStatSpiritClass(true, FilterSpiritNeutral),
                                                         new PlayerStatSpiritClass(true, FilterPrimaryNeutral),
                                                         new PlayerStatSpiritClass(true, FilterSupportNeutral),
                                                         new PlayerStatSpiritClass(true, FilterAffinityAttack),
                                                         new PlayerStatSpiritClass(true, FilterSpiritAttack),
                                                         new PlayerStatSpiritClass(true, FilterPrimaryAttack),
                                                         new PlayerStatSpiritClass(true, FilterSupportAttack),
                                                         new PlayerStatSpiritClass(true, FilterAffinityShield),
                                                         new PlayerStatSpiritClass(true, FilterSpiritShield),
                                                         new PlayerStatSpiritClass(true, FilterPrimaryShield),
                                                         new PlayerStatSpiritClass(true, FilterSupportShield),
                                                         new PlayerStatSpiritClass(true, FilterAffinityGrab),
                                                         new PlayerStatSpiritClass(true, FilterSpiritGrab),
                                                         new PlayerStatSpiritClass(true, FilterPrimaryGrab),
                                                         new PlayerStatSpiritClass(true, FilterSupportGrab),
                                                         new PlayerStatDivider()
                                                     };
}